#define RUEN_AT &ruen_one_key 1 AT // @
#define RUEN_HASH &ruen_one_key 1 HASH // #
#define RUEN_DLR &ruen_one_key 1 DLR // $
#define RUEN_CARET &ruen_one_key 1 CARET // ^
#define RUEN_AMPS &ruen_one_key 1 AMPS // &
#define RUEN_LBRC &ruen_one_key 1 LBRC // [
#define RUEN_LBRK &ruen_one_key 1 LBRK // {
#define RUEN_RBRC &ruen_one_key 1 RBRC // ]
#define RUEN_RBRK &ruen_one_key 1 RBRK // }
#define RUEN_PIPE &ruen_one_key 1 LS(BSLH) // |
#define RUEN_SEMI &ruen_key SEMI LS(N4) // ;
#define RUEN_COLON &ruen_key COLON LS(N6) // :
#define RUEN_APOS &ruen_one_key 1 APOS // '
#define RUEN_DQT &ruen_key DQT LS(N2) // "
#define RUEN_COMMA &ruen_key COMMA LS(FSLH) // ,
#define RUEN_DOT &ruen_key DOT FSLH // .
#define RUEN_LS &ruen_one_key 1 LS // <
#define RUEN_GT &ruen_one_key 1 GT // >
#define RUEN_FSLH &ruen_key FSLH LS(BSLH) // /
#define RUEN_QMARK &ruen_key QMARK LS(N7) // ?
#define RUEN_NMBR &ruen_one_key 0 LS(N3) // №